// @ts-nocheck -- generated by gluestack-ui; upstream Gorhom types exceed TS 6 compatibility.
'use client';
import { FocusScope } from '@gluestack-ui/utils/aria';
import { tva } from '@gluestack-ui/utils/nativewind-utils';
import { Overlay } from '@gluestack-ui/core/overlay/creator';
import GorhomBottomSheet, {
  BottomSheetBackdrop as GorhomBottomSheetBackdrop,
  BottomSheetFlatList as GorhomBottomSheetFlatList,
  BottomSheetFooter as GorhomBottomSheetFooter,
  BottomSheetHandle as GorhomBottomSheetHandle,
  BottomSheetTextInput as GorhomBottomSheetInput,
  BottomSheetScrollView as GorhomBottomSheetScrollView,
  BottomSheetSectionList as GorhomBottomSheetSectionList,
  BottomSheetView as GorhomBottomSheetView,
  type BottomSheetBackdropProps,
} from '@gorhom/bottom-sheet';
import { styled } from 'nativewind';
import React, {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';
import type { PressableProps, TextInputProps, TextProps } from 'react-native';
import { Keyboard, Platform, Text, View } from 'react-native';
import { Pressable as RNPressable } from 'react-native';
import { Pressable as GGHPressable } from 'react-native-gesture-handler';

const bottomSheetBackdropStyle = tva({
  base: 'absolute inset-0 bg-black opacity-50',
});

const bottomSheetContentStyle = tva({
  base: 'px-4 gap-2',
});

const bottomSheetTriggerStyle = tva({
  base: 'p-4 rounded-lg border border-border/90',
});

const bottomSheetHandleStyle = tva({
  base: 'py-3 w-full items-center rounded-t-xl',
});

const bottomSheetItemStyle = tva({
  base: 'p-3 flex-row items-center rounded-sm w-full disabled:opacity-40 web:pointer-events-auto disabled:cursor-not-allowed hover:bg-accent/40 active:bg-accent/50 data-[focus=true]:bg-accent/20 web:data-[focus-visible=true]:bg-accent/40',
});
const bottomSheetItemTextStyle = tva({
  base: 'text-foreground font-normal text-sm',
});

const bottomSheetFooterStyle = tva({
  base: 'p-4 border-t border-border/90',
});

const bottomSheetTextInputStyle = tva({
  base: 'flex-1 text-foreground text-sm md:text-sm py-1 placeholder:text-muted-foreground  web:outline-none ios:leading-[0px] web:cursor-text  h-9 w-full flex-row items-center rounded-md border border-border dark:bg-input/30 bg-transparent shadow-xs overflow-hidden px-3 gap-2',
});

type BottomSheetContextValue = {
  bottomSheetRef: React.RefObject<GorhomBottomSheet>;
  handleClose: () => void;
  handleOpen: (index?: number) => void;
  isVisible: boolean;
  handleSheetChanges: (index: number) => void;
  handleSheetAnimate: (toIndex: number) => void;
  currentIndex: number;
  openRequestId: number;
};

const BottomSheetContext = createContext<BottomSheetContextValue>({
  bottomSheetRef: { current: null! },
  handleClose: () => { },
  handleOpen: () => { },
  isVisible: false,
  handleSheetChanges: () => { },
  handleSheetAnimate: () => { },
  currentIndex: -1,
  openRequestId: 0,
});

export type BottomSheetRef = {
  open: (index?: number) => void;
  close: () => void;
  snapToIndex: (index: number) => void;
  expand: () => void;
  collapse: () => void;
};

type IBottomSheetRootProps = {
  defaultSnapIndex?: number;
  children?: React.ReactNode;
  onOpen?: () => void;
  onClose?: () => void;
  onChange?: (index: number) => void;
};

export const BottomSheet = forwardRef<BottomSheetRef, IBottomSheetRootProps>(
  ({ defaultSnapIndex = 0, onOpen, onClose, onChange, children }, ref) => {
    const bottomSheetRef = useRef<GorhomBottomSheet>(null);
    const [isVisible, setIsVisible] = useState(false);
    const [currentIndex, setCurrentIndex] = useState(-1);
    const [openRequestId, setOpenRequestId] = useState(0);
    const shouldBeOpenRef = useRef(false);
    const targetIndexRef = useRef(defaultSnapIndex);

    const handleOpen = useCallback(
      (index?: number) => {
        const targetIndex = index ?? defaultSnapIndex;
        shouldBeOpenRef.current = true;
        targetIndexRef.current = targetIndex;
        setIsVisible(true);
        setCurrentIndex(targetIndex);
        setOpenRequestId((requestId) => requestId + 1);

        // Re-open an already mounted sheet immediately. BottomSheetPortal
        // repeats this request after mount as a fallback for a null ref.
        bottomSheetRef.current?.snapToIndex(targetIndex);

        onOpen?.();
      },
      [defaultSnapIndex, onOpen]
    );

    const handleClose = useCallback(() => {
      shouldBeOpenRef.current = false;
      Keyboard.dismiss();
      if (bottomSheetRef.current) {
        bottomSheetRef.current.close();
      } else {
        setCurrentIndex(-1);
        setIsVisible(false);
      }
    }, []);

    const handleSheetChanges = useCallback(
      (index: number) => {
        setCurrentIndex(index);
        onChange?.(index);
        if (index === -1) {
          // A close animation can finish after another toolbar press. Keep
          // the newer open request instead of letting this stale event hide it.
          if (shouldBeOpenRef.current) {
            setCurrentIndex(targetIndexRef.current);
            setIsVisible(true);
            setOpenRequestId((requestId) => requestId + 1);
            return;
          }

          setIsVisible(false);
          onClose?.();
        } else {
          targetIndexRef.current = index;
          setIsVisible(true);
        }
      },
      [onClose, onChange]
    );

    const handleSheetAnimate = useCallback((toIndex: number) => {
      if (toIndex === -1) {
        shouldBeOpenRef.current = false;
      }
    }, []);

    const snapToIndex = useCallback((index: number) => {
      shouldBeOpenRef.current = true;
      targetIndexRef.current = index;
      setCurrentIndex(index);
      setIsVisible(true);
      setOpenRequestId((requestId) => requestId + 1);
      bottomSheetRef.current?.snapToIndex(index);
    }, []);

    const expand = useCallback(() => {
      bottomSheetRef.current?.expand();
    }, []);

    const collapse = useCallback(() => {
      bottomSheetRef.current?.collapse();
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        open: handleOpen,
        close: handleClose,
        snapToIndex,
        expand,
        collapse,
      }),
      [handleOpen, handleClose, snapToIndex, expand, collapse]
    );

    const contextValue = useMemo(
      () => ({
        bottomSheetRef,
        handleClose,
        handleOpen,
        isVisible,
        handleSheetChanges,
        handleSheetAnimate,
        currentIndex,
        openRequestId,
      }),
      [
        handleClose,
        handleOpen,
        isVisible,
        handleSheetChanges,
        handleSheetAnimate,
        currentIndex,
        openRequestId,
      ]
    );

    return (
      <BottomSheetContext.Provider value={contextValue}>
        {children}
      </BottomSheetContext.Provider>
    );
  }
);

BottomSheet.displayName = 'BottomSheet';

const StyledGorhomBottomSheet = styled(GorhomBottomSheet, {
  className: 'style',
  backgroundClassName: 'backgroundStyle',
  handleIndicatorClassName: 'handleIndicatorStyle',
});

type IBottomSheetPortalProps = Omit<
  React.ComponentProps<typeof GorhomBottomSheet>,
  'ref' | 'index'
> & {
  className?: string;
  backgroundClassName?: string;
  handleIndicatorClassName?: string;
};

export const BottomSheetPortal = ({
  className,
  backgroundClassName,
  handleIndicatorClassName,
  enablePanDownToClose = true,
  enableDynamicSizing = false,
  snapPoints,
  onChange,
  onAnimate,
  ...props
}: IBottomSheetPortalProps) => {
  const {
    bottomSheetRef,
    handleSheetChanges,
    handleSheetAnimate,
    isVisible,
    currentIndex,
    openRequestId,
  } = useContext(BottomSheetContext);

  const memoizedSnapPoints = useMemo(
    () => snapPoints,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [JSON.stringify(snapPoints)]
  );

  // Defensive index check to prevent Invariant Violation
  const validIndex =
    memoizedSnapPoints && memoizedSnapPoints.length > 0
      ? Math.min(currentIndex, memoizedSnapPoints.length - 1)
      : currentIndex;
  const requestedIndexRef = useRef(validIndex);
  requestedIndexRef.current = validIndex;

  useEffect(() => {
    if (!isVisible || validIndex < 0) return;

    // This effect runs after the portal and native sheet ref have committed,
    // so every press gets a reliable snap even on the first open.
    const animationFrame = requestAnimationFrame(() => {
      bottomSheetRef.current?.snapToIndex(requestedIndexRef.current);
    });

    return () => cancelAnimationFrame(animationFrame);
  }, [bottomSheetRef, isVisible, openRequestId]);

  if (!isVisible) return null;

  return (
    <Overlay isOpen={true} isKeyboardDismissable={false} style={{ flex: 1 }}>
      <StyledGorhomBottomSheet
        ref={bottomSheetRef}
        snapPoints={memoizedSnapPoints}
        index={validIndex}
        // Consumers render BottomSheetDragIndicator as the sheet handle.
        // Disable Gorhom's default handle so only one indicator is shown.
        handleComponent={() => null}
        enableDynamicSizing={enableDynamicSizing}
        onChange={(idx) => {
          handleSheetChanges(idx);
          onChange?.(idx);
        }}
        onAnimate={(fromIndex, toIndex, fromPosition, toPosition) => {
          handleSheetAnimate(toIndex);
          onAnimate?.(fromIndex, toIndex, fromPosition, toPosition);
        }}
        enablePanDownToClose={enablePanDownToClose}
        // @ts-ignore
        className={className}
        // @ts-ignore
        backgroundClassName={`${backgroundClassName} bg-background border border-border/90 rounded-xl`}
        // @ts-ignore
        handleIndicatorClassName={`${handleIndicatorClassName} bg-primary`}
        {...props}
      >
        {props.children}
      </StyledGorhomBottomSheet>
    </Overlay>
  );
};

export const BottomSheetTrigger = ({
  className,
  index,
  onPress,
  ...props
}: PressableProps & { className?: string; index?: number }) => {
  const { handleOpen } = useContext(BottomSheetContext);
  return (
    <RNPressable
      {...props}
      onPress={(e) => {
        onPress?.(e);
        handleOpen(index);
      }}
      className={bottomSheetTriggerStyle({ className })}
    >
      {props.children}
    </RNPressable>
  );
};

type IBottomSheetBackdropProps = BottomSheetBackdropProps & {
  className?: string;
};

export const BottomSheetBackdrop = ({
  disappearsOnIndex = -1,
  appearsOnIndex = 0,
  opacity = 0.5,
  className,
  pressBehavior = 'close',
  ...props
}: Partial<IBottomSheetBackdropProps>) => {
  return (
    <GorhomBottomSheetBackdrop
      // @ts-ignore
      className={bottomSheetBackdropStyle({ className })}
      disappearsOnIndex={disappearsOnIndex}
      appearsOnIndex={appearsOnIndex}
      opacity={opacity}
      pressBehavior={pressBehavior}
      {...props}
    />
  );
};

const StyledGorhomBottomSheetHandle = styled(GorhomBottomSheetHandle, {
  className: 'style',
});

type IBottomSheetHandleProps = React.ComponentProps<
  typeof GorhomBottomSheetHandle
> & {
  className?: string;
  indicatorClassName?: string;
};

export const BottomSheetDragIndicator = ({
  children,
  className,
  indicatorClassName,
  ...props
}: Partial<IBottomSheetHandleProps>) => {
  return (
    <StyledGorhomBottomSheetHandle
      {...props}
      // @ts-ignore
      className={bottomSheetHandleStyle({ className })}
    >
      {children}
    </StyledGorhomBottomSheetHandle>
  );
};

const StyledGorhomBottomSheetView = styled(GorhomBottomSheetView, {
  className: 'style',
});

type IBottomSheetContentProps = React.ComponentProps<
  typeof GorhomBottomSheetView
> & {
  className?: string;
  focusScope?: boolean;
};

export const BottomSheetContent = ({
  className,
  focusScope = true,
  ...props
}: IBottomSheetContentProps) => {
  const { handleClose, isVisible } = useContext(BottomSheetContext);

  const keyDownHandlers = useMemo(() => {
    if (Platform.OS !== 'web') return {};
    return {
      onKeyDown: (e: React.KeyboardEvent) => {
        if (e.key === 'Escape') {
          e.preventDefault();
          handleClose();
        }
      },
    };
  }, [handleClose]);

  const content = props.children;
  const wrappedContent =
    Platform.OS === 'web' && isVisible && focusScope ? (
      <FocusScope contain={isVisible} autoFocus restoreFocus>
        {content}
      </FocusScope>
    ) : (
      content
    );

  return (
    <StyledGorhomBottomSheetView
      {...props}
      // @ts-ignore
      {...keyDownHandlers}
      // @ts-ignore
      className={bottomSheetContentStyle({ className })}
    >
      {wrappedContent}
    </StyledGorhomBottomSheetView>
  );
};

type IBottomSheetFooterProps = React.ComponentProps<
  typeof GorhomBottomSheetFooter
> & {
  className?: string;
  children?: React.ReactNode;
};

export const BottomSheetFooter = ({
  className,
  children,
  ...props
}: IBottomSheetFooterProps) => {
  return (
    <GorhomBottomSheetFooter {...props}>
      <View
        // @ts-ignore
        className={bottomSheetFooterStyle({ className })}
      >
        {children}
      </View>
    </GorhomBottomSheetFooter>
  );
};

type IBottomSheetItemProps = PressableProps & {
  className?: string;
  closeOnSelect?: boolean;
};

const StyledGGHPressable = styled(GGHPressable, {
  className: 'style',
});

export const BottomSheetItem = ({
  children,
  className,
  closeOnSelect = true,
  ...props
}: IBottomSheetItemProps) => {
  const { handleClose } = useContext(BottomSheetContext);

  const Pressable = Platform.OS === 'web' ? RNPressable : StyledGGHPressable;

  return (
    <Pressable
      {...props}
      // @ts-ignore
      className={bottomSheetItemStyle({ className })}
      onPress={(e) => {
        props.onPress?.(e);
        if (closeOnSelect) {
          handleClose();
        }
      }}
      role="button"
      accessibilityRole="button"
    >
      {children}
    </Pressable>
  );
};

type IBottomSheetItemTextProps = TextProps & {
  className?: string;
};

export const BottomSheetItemText = ({
  className,
  ...props
}: IBottomSheetItemTextProps) => {
  return (
    <Text {...props} className={bottomSheetItemTextStyle({ className })} />
  );
};

const StyledGorhomBottomSheetInput = styled(GorhomBottomSheetInput, {
  className: 'style',
});

export const BottomSheetTextInput = ({
  className,
  ...props
}: TextInputProps) => {
  return (
    <StyledGorhomBottomSheetInput
      {...props}
      // @ts-ignore
      className={bottomSheetTextInputStyle({ className })}
    />
  );
};

// Scrollable components
export const BottomSheetScrollView = GorhomBottomSheetScrollView;
export const BottomSheetFlatList = GorhomBottomSheetFlatList;
export const BottomSheetSectionList = GorhomBottomSheetSectionList;
